### ISSUE TITLE
unable to sign nodes with namespace prefix

### ISSUE THREAD

**Issue by paulish** [yaronn/xml-crypto#201]
here is xml:
```xml
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
  <soap:Header>
    <wsa:MessageID wsu:Id="id-9b50f86a-e0bb-47cc-ba3a-419b4f1cd4ec">38a8a055-8164-4738-a2f8-46bbc26ebb2a</wsa:MessageID>
    <wsa:Action wsu:Id="id-1e5921e0-a346-47f2-9888-571c6361e56b">registerDocument</wsa:Action>
    <wsa:ReplyTo wsu:Id="id-628661eb-a354-429b-a81d-5c9911fcf9f3"><Address>http://www.w3.org/2005/08/addressing/anonymous</Address></wsa:ReplyTo>
    <wsa:To wsu:Id="id-127ff435-8ec6-4698-a988-8d6bad9518aa">http://www.w3.org/2005/08/addressing/anonymous</wsa:To>
  </soap:Header>
  <soap:Body wsu:Id="BODY-5909a7c5-99d1-453f-a5d0-4f8b1254346b">
  </soap:Body>
</soap:Envelope>
```

I want to sign all nodes with `wsu:Id` attribute.

The code to sign is:
```javascript
let sig = new xmlCrypto.SignedXml('', {
    signatureAlgorithm: algorithms.signatureAlgorithm
});

sig.addReference(
    '//*[@wsu:Id]',
    ["http://www.w3.org/2001/10/xml-exc-c14n#"],
    algorithms.digestAlgorithm
);

sig.computeSignature(xml);
```

The problem is that there is no way to pass namespaces to xpath. And that no default namespace resolver is used.

The error I get:
```
Error: Cannot resolve QName wsu
    at Function.NodeTest.nameSpaceMatches (c:\programming\web\gitlab\xml\node_modules\xpath\xpath.js:2311:15)
    at Object.matches (c:\programming\web\gitlab\xml\node_modules\xpath\xpath.js:2337:16)
    at Function.PathExpr.applyStep (c:\programming\web\gitlab\xml\node_modules\xpath\xpath.js:1855:27)
    at c:\programming\web\gitlab\xml\node_modules\xpath\xpath.js:2046:67
   ...
```

**Comment by Sufyan7262** [comment]
Any Solution for this?

**Comment by paulish** [comment]
A workaround is to use xpath `//*[@*[local-name()='Id' and namespace-uri()='http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd']]` instead of `//*[@wsu:Id]`.

But it would be better imo to create an uri resolver instance inside of xml-crypto code and to use `selectWithResolver` method instead of `select`.

**Comment by paulish** [comment]
Added pr #218

**Comment by Sufyan7262** [comment]
```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cat="http://schemas.kvk.nl/schemas/hrip/catalogus/2015/02" xmlns:tns="http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02">
   <soap:Header>
      <wsa:Action Id="_0" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns="http://www.w3.org/2005/08/addressing">http://es.kvk.nl/ophalenInschrijving</wsa:Action>
      <wsa:To Id="_1" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns="http://www.w3.org/2005/08/addressing">http://es.kvk.nl/kvk-DataservicePP/2015/02</wsa:To>
      <wsa:MessageID Id="_2" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns="http://www.w3.org/2005/08/addressing">uuid:5ed338e7-67b8-4ddc-abb5-6ed6a75690b7</wsa:MessageID>
      <wsse:Security soap:mustUnderstand="1" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
         <wsse:BinarySecurityToken EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary" ValueType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3" wsu:Id="x509-e0ec781c05da40abb950da73c9cecb97">${publicCert}</wsse:BinarySecurityToken>
         <Timestamp Id="_1" xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">
            <Created>2020-10-19T07:52:31Z</Created>
            <Expires>2020-10-19T08:02:31Z</Expires>
         </Timestamp>
      </wsse:Security>
   </soap:Header>
   <soap:Body Id="_0">
      <ophalenInschrijvingRequest xmlns="http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02">
         <klantreferentie>SoapUI-TEST</klantreferentie>
         <kvkNummer>90004604</kvkNummer>
      </ophalenInschrijvingRequest>
   </soap:Body>
</soap:Envelope>
```
